sudo: required
dist: trusty
language: node_js
node_js:
  - 9
install:
  - npm install
script:
  - npm run build
after_success: |
	if [ -n "$TRAVIS_TAG" ]; then
    echo "Has tag"
  else
    echo "No has tag"
	fi
