sudo: required
dist: trusty
language: node_js
node_js:
  - 9
install:
  - npm install
script:
  - npm run build
after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    git clone https://github.com/systelab/systelab.github.io.git
    rm -rf ./systelab.github.io/allure-reporter-test/*
    cp -r ./dist/* ./systelab.github.io/allure-reporter-test
    sed -i -e "s~base href=\"/\"~base href=\"/allure-reporter-test/\"~g" ./systelab.github.io/allure-reporter-test/index.html
    cd systelab.github.io
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'New deploy in test environment from Travis'
    git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
  fi
	if ["$TRAVIS_TAG"]; then
	  git clone https://github.com/systelab/systelab.github.io.git
	  rm -rf ./systelab.github.io/allure-reporter/*
	  cp -r ./dist/* ./systelab.github.io/allure-reporter
	  sed -i -e "s~base href=\"/\"~base href=\"/allure-reporter/\"~g" ./systelab.github.io/allure-reporter/index.html
	  cd systelab.github.io
	  git add .
	  git -c user.name='travis' -c user.email='travis' commit -m 'New deploy in production from Travis'
	  git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
	fi
