sudo: required
dist: trusty
language: node_js
node_js:
  - 9
install:
  - npm install
script:
  - npm run build
after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ branch == master ]; then
    git clone https://github.com/systelab/systelab.github.io.git
    rm ./systelab.github.io/allure-reporter/*
    cp ./dist/* ./systelab.github.io/allure-reporter
    sed -i -e "s~base href=\"/\"~base href=\"/allure-reporter/\"~g" ./systelab.github.io/allure-reporter/index.html
    cd systelab.github.io
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m 'New deploy from Travis'
    git push -f -q https://systelab:$GITHUB_API_KEY@github.com/systelab/systelab.github.io
  fi
